



hipchat:
  jid: 8618_364462@chat.hipchat.com
  room_nickname: Michael Dometita
  host: chat.hipchat.com
  port: 5222
  muc_domain: conf.hipchat.com
  
  rooms:
    tracksimple: 8618_tracksimple
    white_noise: 8618_bk_white_noise
  